id: using-docker-kubernetes-to-manage-liferay-deployments
title: Using Docker & Kubernetes to manage Liferay deployments
thumbnail: https://0701.static.prezi.com/preview/rmbry32hnvkye5yasv6oprdyzh6jc3sachvcdoaizecfr3dnitcq_0_0.png
url: https://prezi.com/2cjip6hn6yvw/using-docker-kubernetes-to-manage-liferay-deployments/
premiere: 2015-10-07
abstract: ''
