id: event-driven-from-cool-concept-to-solid-applications
title: Event-driven - from a cool concept to solid applications
thumbnail: https://slidrio-decks.global.ssl.fastly.net/1864/thumbs/1_1280.jpg
url: https://slidr.io/azzazzel/event-driven-from-a-cool-concept-to-solid-applications
premiere: 2022-04-14
abstract: ''
